#! /bin/sh

# run like sh install-test python<VERSION>
# run like sh install-test python2
# run like sh install-test python3

# remove old venvs
rm -rf venv/;

echo '\n------ ACTIVATING VIRTUALENV ------\n'
virtualenv --python=$1 --no-site-packages venv;
source venv/bin/activate;

echo '\n------ INSTALLING JARJAR ------\n'
pip install ../. --force-reinstall;

echo '\n------ USAGE TESTS ------\n'

echo 'Which jarjar?'
which jarjar
echo "Exit: $?\n"

echo 'Send a message?'
jarjar -m 'Test!'
echo "Exit: $?\n"

echo 'Run a task?'
jarjar sleep 1 -m i took a nap..
echo "Exit: $?\n"

echo '------ TEST COMPLETE ------'
