#! /bin/sh

# run like sh install-venv python<VERSION>
# sh install-venv python2
# sh install-venv python3

# remove old venvs
rm -rf venv/;

echo '\n------ ACTIVATING VIRTUALENV ------\n'
virtualenv --python=$1 --no-site-packages venv;
source venv/bin/activate;

echo '\n------ INSTALLING JARJAR ------\n'
pip install ../. --force-reinstall;

echo '\n------ USAGE TESTS ------\n'

echo 'Which jarjar?'
which jarjar
echo "Exit: $?\n"

echo 'Send a message?'
jarjar -m This is a $1 test message.
echo "Exit: $?\n"

echo 'Run a task?'
jarjar sleep 1 -m This is a $1 test attachment.
echo "Exit: $?\n"

echo '------ TEST COMPLETE ------'
