#! /bin/sh

# remove old venvs
echo '\n------ CLEARING ENV ------\n'
deactivate;
rm -rf venv/;

echo '\n------ INSTALLING VIRTUALENV ------\n'
virtualenv --python=python3 venv;

echo '\n------ ACTIVATING VIRTUALENV ------\n'
source venv/bin/activate;

echo '\n------ INSTALLING JARJAR ------\n'
pip install ../. --force-reinstall;

echo '\n------ USAGE TESTS ------\n'

echo 'Which jarjar?'
which jarjar
echo "Exit: $?\n"

echo 'Send a message?'
jarjar -m 'Test!'
echo "Exit: $?\n"

echo 'Run a task?'
jarjar sleep 1 -m i took a nap..
echo "Exit: $?\n"

echo '------ TEST COMPLETE ------'
